// <auto-generated />
namespace OnlineRecipes.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class Implementrequiredrangeinreciperatingandimageurl : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Implementrequiredrangeinreciperatingandimageurl));
        
        string IMigrationMetadata.Id
        {
            get { return "202006220917002_Implement required range in recipe rating, and image url"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
