// <auto-generated />
namespace OnlineRecipes.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class Addrecipecategories : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Addrecipecategories));
        
        string IMigrationMetadata.Id
        {
            get { return "202006221803078_Add recipe categories"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
